apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-admins-group.yaml
  - openshift-gitops-operator-subscription.yaml
  - openshift-gitops-argocd.yaml
  - openshift-gitops-cluster-admin-crb.yaml